version: '3.9'

services:
  db:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.30
    ports:
      - 7700:7700
    volumes:
      - /var/local/meilisearch:/data.ms
    restart: unless-stopped

  rabbitmq:
    hostname: rabbit
    container_name: rabbitmq
    image: arm64v8/rabbitmq:3.11.5-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /var/local/rabbitmq:/var/lib/rabbitmq/mnesia/
    

